version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
